aime25:
  resources_servers:
    aime25:
      entrypoint: app.py
      domain: math
      verified: false
aime25_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: aime25
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
        - name: train
          type: train
          jsonl_fpath: resources_servers/aime25/data/train.jsonl
          gitlab_identifier:
            dataset_name: aime25
            version: 0.0.1
            artifact_fpath: train.jsonl
          license: Apache 2.0
        - name: validation
          type: validation
          jsonl_fpath: resources_servers/aime25/data/validation.jsonl
          gitlab_identifier:
            dataset_name: aime25
            version: 0.0.1
            artifact_fpath: validation.jsonl
          license: Apache 2.0
        - name: example
          type: example
          jsonl_fpath: resources_servers/aime25/data/example.jsonl
