math_with_judge:
  resources_servers:
    math_with_judge:
      judge_model_server:
        type: responses_api_models
        name: qwen3_30ba3b_instruct_2507_model_server
      judge_responses_create_params:
        input: []
      should_use_judge: true
      verified: false
qwen3_30ba3b_instruct_2507_model_server:
  responses_api_models:
    local_vllm_model:
      entrypoint: app.py
      model: Qwen/Qwen3-30B-A3B-Instruct-2507
      hf_home: null
      vllm_serve_kwargs:
        data_parallel_size: 1
        tensor_parallel_size: 8
        pipeline_parallel_size: 1
        gpu_memory_utilization: 0.9
        enable_auto_tool_choice: true
        tool_call_parser: hermes
      return_token_id_information: false
      uses_reasoning_parser: true
