translation_bleu_resources_server:
  resources_servers:
    translation_bleu:
      domain: translation
      entrypoint: app.py
translation_bleu_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: translation_bleu_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/translation_bleu/data/train.jsonl
        num_repeats: 1
        gitlab_identifier:
          dataset_name: translation_bleu
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/translation_bleu/data/validation.jsonl
        num_repeats: 1
        gitlab_identifier:
          dataset_name: translation_bleu
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/translation_bleu/data/example.jsonl
        num_repeats: 1
