library_judge_math:
  resources_servers:
    library_judge_math:
      entrypoint: app.py
      judge_model_server:
        type: responses_api_models
        name: ???
      judge_responses_create_params: {
        input: []
      }
      should_use_judge: false
parallel_reasoning_simple_agent:
  responses_api_agents:
    parallel_reasoning_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: library_judge_math
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/library_judge_math/data/bytedtsinghua_style_aime24.jsonl
        gitlab_identifier:
          dataset_name: bytedtsinghua_style_aime24
          version: 0.0.1
          artifact_fpath: bytedtsinghua_style_aime24.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/library_judge_math/data/example.jsonl
      num_parallelizer: 2
      num_executor: 4
      num_reducer: 1
      executor_max_output_tokens: 32768
      parallel_type: planner
      keep_executor_prompt: true
      use_reducer: true
      reducer_type: genselect
      reduce_across: all
      return_reducer_only: false
