gdpval_agent:
  responses_api_agents:
    gdpval_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: ???
      model_server:
        type: responses_api_models
        name: policy_model
      max_steps: 100
      max_tokens: 10000
      context_summarization_cutoff: 0.7
      step_warning_threshold: 80
