terminal_pivot:
  resources_servers:
    terminal_pivot:
      entrypoint: app.py
      domain: agent
      verified: false
      description: terminal based problems
      value: Improve terminal based problems
terminal_pivot_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      max_steps: 1
      resources_server:
        type: resources_servers
        name: terminal_pivot
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/terminal_pivot/data/train.jsonl
        gitlab_identifier:
          dataset_name: terminal_pivot
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/terminal_pivot/data/validation.jsonl
        gitlab_identifier:
          dataset_name: terminal_pivot
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/terminal_pivot/data/example.jsonl
