berman_agent:
  responses_api_agents:
    berman_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: arc_agi
      model_server:
        type: responses_api_models
        name: policy_model

      num_initial_candidates: 5
      num_top_for_revision: 5
      num_pooled_candidates: 2
      initial_temperature: 0.9