newton_bench:
  resources_servers:
    newton_bench:
      entrypoint: app.py
      host: 127.0.0.1
      port: 8000
      domain: math
      verified: false
newton_bench_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      host: 127.0.0.1
      port: 8001
      resources_server:
        type: resources_servers
        name: newton_bench
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/newton_bench/data/train.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/newton_bench/data/example.jsonl
        license: Apache 2.0
