letter_counting_atropos_resources_server:
  resources_servers:
    atropos:
      entrypoint: letter_counting_app.py

letter_counting_atropos_agent:
  responses_api_agents:
    atropos_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: letter_counting_atropos_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
