# Multi-Turn Tool Calling
tool_calling_atropos_resources_server:
  resources_servers:
    atropos:
      entrypoint: tool_calling_app.py

tool_calling_atropos_agent:
  responses_api_agents:
    atropos_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: tool_calling_atropos_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
