gpt-4_1-2025-04-14:
  responses_api_models:
    openai_model:
      entrypoint: app.py
      openai_base_url: https://api.openai.com/v1
      openai_api_key: ???
      openai_model: gpt-4.1-2025-04-14

      extra_body:
        max_output_tokens: null
