policy_api_key: ???
gpt-4.1-2025-04-14:
  responses_api_models:
    openai_model:
      entrypoint: app.py
      openai_base_url: https://api.openai.com/v1
      openai_api_key: ${policy_api_key}
      openai_model: gpt-4.1-2025-04-14
