calendar:
  resources_servers:
    calendar:
      entrypoint: app.py
      domain: agent
      verified: false
calendar_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: calendar
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/calendar/data/train.jsonl
        gitlab_identifier:
          dataset_name: calendar
          version: 0.0.1
          artifact_fpath: calendar/train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/calendar/data/validation.jsonl
        gitlab_identifier:
          dataset_name: calendar
          version: 0.0.1
          artifact_fpath: calendar/validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/calendar/data/example.jsonl
