terminus_format:
  resources_servers:
    terminus_format:
      entrypoint: app.py
      domain: instruction_following
      verified: false
terminus_format_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: terminus_format
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/terminus_format/data/train.jsonl
        num_repeats: 1
        gitlab_identifier:
          dataset_name: terminus_format
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/terminus_format/data/validation.jsonl
        num_repeats: 1
        gitlab_identifier:
          dataset_name: terminus_format
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/terminus_format/data/example.jsonl
        num_repeats: 1
