bixbench_aviary_resources_server:
  resources_servers:
    aviary:
      entrypoint: bixbench_app.py
bixbench_aviary_agent:
  responses_api_agents:
    aviary_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: bixbench_aviary_resources_server
      model_server:
        type: responses_api_models
        name: policy_model