bixbench_repl_aviary_resources_server:
  resources_servers:
    aviary:
      entrypoint: repl_app.py
      domain: coding
      verified: false
bixbench_repl_aviary_agent:
  responses_api_agents:
    aviary_agent:
      entrypoint: app.py
      max_steps: 10
      resources_server:
        type: resources_servers
        name: bixbench_repl_aviary_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
