arc_agi_2:
  resources_servers:
    arc_agi:
      entrypoint: app.py
arc_agi_2_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      host: 127.0.0.1
      port: 15215
      resources_server:
        type: resources_servers
        name: arc_agi_2
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: example_2
        type: example
        jsonl_fpath: resources_servers/arc_agi/data/example_2.jsonl
      - name: training_2
        type: validation
        jsonl_fpath: resources_servers/arc_agi/data/arc_agi_2_training.jsonl
      - name: evaluation_2
        type: validation
        jsonl_fpath: resources_servers/arc_agi/data/arc_agi_2_evaluation.jsonl