policy_model:
  responses_api_models:
    local_vllm_model:
      entrypoint: app.py
      model: ???
      # Gym will materialize the `{model}`, `{host}`, and `{port}` and substitute any values in vllm_spinup_command_template_kwargs as well.
      # If a hf_token is present in the 
      vllm_spinup_command: |
        HF_HOME=.cache/ \
        HF_HUB_ENABLE_HF_TRANSFER=1 \
            hf download {model}

        HF_HOME=.cache/ \
        HOME=. \
        vllm serve \
            {model} \
            --dtype auto \
            --tensor-parallel-size 4 \
            --gpu-memory-utilization 0.9 \
            --enable-auto-tool-choice \
            --tool-call-parser hermes \
            --host {host} \
            --port {port}
      vllm_spinup_command_template_kwargs: {}

      return_token_id_information: false
      uses_reasoning_parser: true
