noop:
  resources_servers:
    noop:
      entrypoint: app.py
      domain: other
      reward: 1.0
noop_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: noop
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/noop/data/example.jsonl
