crowdstrike_logscale_syntax_resources_server:
  resources_servers:
    crowdstrike_logscale_syntax:
      entrypoint: app.py
      domain: e2e
      judge_model:
        type: responses_api_models
        name: crowdstrike_logscale_syntax_judge_model
crowdstrike_logscale_syntax_judge_model:
  responses_api_models:
    openai_model:
      entrypoint: app.py
      openai_base_url: https://api.openai.com/v1
      openai_api_key: ???
      openai_model: gpt-4.1-2025-04-14
crowdstrike_logscale_syntax_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: crowdstrike_logscale_syntax_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/crowdstrike_logscale_syntax/data/validation.jsonl
        num_repeats: 8
        gitlab_identifier:
          dataset_name: crowdstrike_logscale_syntax
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/crowdstrike_logscale_syntax/data/example.jsonl
        num_repeats: 1
