aviary_wrapper_resources_server:
  resources_servers:
    aviary_wrapper:
      entrypoint: app.py
      max_steps: 10
      correct_reward: 1.0
      incorrect_reward: 0.0
aviary_wrapper_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: aviary_wrapper_resources_server
      model_server:
        type: responses_api_models
        name: vllm_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/aviary_wrapper/data/train.jsonl
        gitlab_identifier:
          dataset_name: aviary_wrapper
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/aviary_wrapper/data/validation.jsonl
        gitlab_identifier:
          dataset_name: aviary_wrapper
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/aviary_wrapper/data/example.jsonl
