offline_search_resources_server:
  resources_servers:
    offline_search:
      entrypoint: app.py
offline_search_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: offline_search_resources_server
      model_server:
        type: responses_api_models
        name: openai_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/offline_search/data/MCQA_syn_gpqa_1_2_difficulty_filtered/train.jsonl
        gitlab_identifier:
          dataset_name: offline_search_MCQA_syn_hle
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: train
        type: train
        jsonl_fpath: resources_servers/offline_search/data/MCQA_syn_hle/train.jsonl
        gitlab_identifier:
          dataset_name: offline_search
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: example_MCQA_syn_gpqa_1_2
        type: example
        jsonl_fpath: resources_servers/offline_search/data/MCQA_syn_gpqa_1_2_difficulty_filtered/examples.jsonl
      - name: example_MCQA_syn_hle
        type: example
        jsonl_fpath: resources_servers/offline_search/data/MCQA_syn_hle/examples.jsonl
