constant_reward:
  resources_servers:
    constant_reward:
      entrypoint: app.py
      domain: other
      verified: False
constant_reward_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: constant_reward
      model_server:
        type: responses_api_models
        name: policy_model
      max_steps: 1
