vllm_model:
  responses_api_models:
    vllm_model:
      entrypoint: app.py
      base_url: http://localhost:10240/v1
      api_key: fake-api-key
      model: Qwen/Qwen3-30B-A3B
      return_token_id_information: false
