cobol_compiler:
  resources_servers:
    cobol_compiler:
      entrypoint: app.py
      domain: coding
      num_processes: 8
      timeout_secs: 30
      compiler_command: cobc
      compiler_flags:
      - -x
      - -free
      - -fdiagnostics-plain-output
      debug: false
cobol_compiler_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: cobol_compiler
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: cobol_multipl_eval
        type: train
        jsonl_fpath: resources_servers/cobol_compiler/data/cobol_multipl_eval.jsonl
        license: MIT
        num_repeats: 1
      - name: example
        type: example
        jsonl_fpath: resources_servers/cobol_compiler/data/example.jsonl
cobol_compiler_eval_agent:
  responses_api_agents:
    cobol_eval_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: cobol_compiler
      model_server:
        type: responses_api_models
        name: policy_model
      max_correction_turns: 3
      datasets:
      - name: cobol_multipl_eval
        type: train
        jsonl_fpath: resources_servers/cobol_compiler/data/cobol_multipl_eval.jsonl
        license: MIT
        num_repeats: 1
      - name: example
        type: example
        jsonl_fpath: resources_servers/cobol_compiler/data/example.jsonl
