# This resources server is unused. It's just here as a placeholder for meta information
mini_swe_resource_resources_server:
  resources_servers:
    mini_swe_resource:
      entrypoint: app.py
      domain: coding
      verified: false
mini_swe_main_agent_train:
  responses_api_agents:
    mini_swe_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: mini_swe_resource_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/mini_swe_resource/data/train.jsonl
        gitlab_identifier:
          dataset_name: mini_swe_agent
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: MIT
        num_repeats: 100  # Just some big repeat number
      - name: example
        type: example
        jsonl_fpath: resources_servers/mini_swe_resource/data/example.jsonl
      concurrency: 16
      env: singularity
      cache_dir_template: ???
      run_golden: False
      step_timeout: 300
      eval_timeout: 900
      skip_if_exists: False
      step_limit: 150
      collapse_limit: 3
mini_swe_main_agent_validation:
  responses_api_agents:
    mini_swe_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: mini_swe_resource_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/mini_swe_resource/data/validation.jsonl
        gitlab_identifier:
          dataset_name: mini_swe_agent
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: MIT
      concurrency: 16
      env: singularity
      cache_dir_template: ???
      run_golden: False
      step_timeout: 300
      eval_timeout: 900
      skip_if_exists: False
      step_limit: 150
      collapse_limit: 3
