my_gpt4p1_simple_model_server:
  responses_api_models:
    simple_model_server:
      entrypoint: app.py
      openai_base_url: https://api.openai.com/v1
      openai_api_key: ???
      openai_model_name: gpt-4.1-2025-04-14
