example_session_state_mgmt_resources_server:
  resources_servers:
    example_session_state_mgmt:
      entrypoint: app.py
      domain: agent
      verified: false
      description: Session state management (in-memory)
example_session_state_mgmt_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: example_session_state_mgmt_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/example_session_state_mgmt/data/train.jsonl
        gitlab_identifier:
          dataset_name: session_state_mgmt
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/example_session_state_mgmt/data/validation.jsonl
        gitlab_identifier:
          dataset_name: session_state_mgmt
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/example_session_state_mgmt/data/example.jsonl
