simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      max_steps: 10
      resources_server:
        type: resources_servers
        name: ???
      model_server:
        type: responses_api_models
        name: openai_model
