simple_sudoku:
  resources_servers:
    simple_sudoku:
      entrypoint: app.py

simple_sudoku_simple_agent:
  responses_api_agents:
    simple_game_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: simple_sudoku
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/simple_sudoku/data/train.jsonl
        gitlab_identifier:
          dataset_name: simple_sudoku
          version: 0.0.2
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/simple_sudoku/data/example.jsonl
